In [1]:
import csv
import numpy as np
import pandas as pd
import reverse_geocoder as rg

In [2]:
df = pd.read_csv("location_pre_20190113_000000000000.csv", compression='gzip')

In [3]:
df.head()

               dsn  latitude  longitude           created_at
0  AC000W001151849   14.5333   -91.6833  2019-01-14 00:25:10
1  AC000W002672712   18.4663   -66.1057  2019-01-14 00:37:49
2  AC000W001073256   21.4063  -157.7448  2019-01-14 00:31:11
3  AC000W002437000   24.7279   -81.0386  2019-01-14 00:59:42
4  AC000W002600666   25.9441   -80.2144  2019-01-14 00:03:32

In [4]:
locations = list(zip(df.latitude.values, df.longitude.values))

In [5]:
# From the github Jeff sent
results2 = rg.search(locations)

Loading formatted geocoded file...

In [6]:
display(results2)

[OrderedDict([('lat', '14.53611'),
              ('lon', '-91.67778'),
              ('name', 'Retalhuleu'),
              ('admin1', 'Retalhuleu'),
              ('admin2', 'Municipio de Retalhuleu'),
              ('cc', 'GT')]),
 OrderedDict([('lat', '18.46633'),
              ('lon', '-66.10572'),
              ('name', 'San Juan'),
              ('admin1', 'San Juan'),
              ('admin2', ''),
              ('cc', 'PR')]),
 OrderedDict([('lat', '21.40241'),
              ('lon', '-157.74054'),
              ('name', 'Kailua'),
              ('admin1', 'Hawaii'),
              ('admin2', 'Honolulu County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '24.71375'),
              ('lon', '-81.09035'),
              ('name', 'Marathon'),
              ('admin1', 'Florida'),
              ('admin2', 'Monroe County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '25.94898'),
              ('lon', '-80.21227'),
              ('name', 'Norland'),
              ('admin1', 'Florida'),
              ('admin2', 'Miami-Dade County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '26.11342'),
              ('lon', '-80.19338'),
              ('name', 'Melrose Park'),
              ('admin1', 'Florida'),
              ('admin2', 'Broward County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '26.24453'),
              ('lon', '-80.20644'),
              ('name', 'Margate'),
              ('admin1', 'Florida'),
              ('admin2', 'Broward County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '26.32646'),
              ('lon', '-98.3853'),
              ('name', 'Citrus City'),
              ('admin1', 'Texas'),
              ('admin2', 'Hidalgo County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '26.71174'),
              ('lon', '-81.86897'),
              ('name', 'Suncoast Estates'),
              ('admin1', 'Florida'),
              ('admin2', 'Lee County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.04422'),
              ('lon', '-82.23593'),
              ('name', 'North Port'),
              ('admin1', 'Florida'),
              ('admin2', 'Sarasota County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.63864'),
              ('lon', '-80.39727'),
              ('name', 'Vero Beach'),
              ('admin1', 'Florida'),
              ('admin2', 'Indian River County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.80058'),
              ('lon', '-97.39638'),
              ('name', 'Corpus Christi'),
              ('admin1', 'Texas'),
              ('admin2', 'Nueces County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.80058'),
              ('lon', '-97.39638'),
              ('name', 'Corpus Christi'),
              ('admin1', 'Texas'),
              ('admin2', 'Nueces County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.86614'),
              ('lon', '-82.32648'),
              ('name', 'Riverview'),
              ('admin1', 'Florida'),
              ('admin2', 'Hillsborough County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.7903'),
              ('lon', '-97.66888'),
              ('name', 'Robstown'),
              ('admin1', 'Texas'),
              ('admin2', 'Nueces County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.87725'),
              ('lon', '-97.32388'),
              ('name', 'Portland'),
              ('admin1', 'Texas'),
              ('admin2', 'San Patricio County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '27.94752'),
              ('lon', '-82.45843'),
              ('name', 'Tampa'),
              ('admin1', 'Florida'),
              ('admin2', 'Hillsborough County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '28.07807'),
              ('lon', '-82.76371'),
              ('name', 'Palm Harbor'),
              ('admin1', 'Florida'),
              ('admin2', 'Pinellas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '28.07224'),
              ('lon', '-80.68006'),
              ('name', 'June Park'),
              ('admin1', 'Florida'),
              ('admin2', 'Brevard County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '28.05641'),
              ('lon', '-82.72788'),
              ('name', 'Saint George'),
              ('admin1', 'Florida'),
              ('admin2', 'Pinellas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.38663'),
              ('lon', '-98.61797'),
              ('name', 'Lackland Air Force Base'),
              ('admin1', 'Texas'),
              ('admin2', 'Bexar County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.47495'),
              ('lon', '-98.45085'),
              ('name', 'Terrell Hills'),
              ('admin1', 'Texas'),
              ('admin2', 'Bexar County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.61968'),
              ('lon', '-95.63495'),
              ('name', 'Sugar Land'),
              ('admin1', 'Texas'),
              ('admin2', 'Fort Bend County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.62607'),
              ('lon', '-95.73162'),
              ('name', 'Pecan Grove'),
              ('admin1', 'Texas'),
              ('admin2', 'Fort Bend County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.62607'),
              ('lon', '-95.73162'),
              ('name', 'Pecan Grove'),
              ('admin1', 'Texas'),
              ('admin2', 'Fort Bend County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.65163'),
              ('lon', '-82.32483'),
              ('name', 'Gainesville'),
              ('admin1', 'Florida'),
              ('admin2', 'Alachua County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.69384'),
              ('lon', '-95.66495'),
              ('name', 'Mission Bend'),
              ('admin1', 'Texas'),
              ('admin2', 'Fort Bend County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.75163'),
              ('lon', '-82.42483'),
              ('name', 'Alachua'),
              ('admin1', 'Florida'),
              ('admin2', 'Alachua County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.71801'),
              ('lon', '-95.43383'),
              ('name', 'West University Place'),
              ('admin1', 'Texas'),
              ('admin2', 'Harris County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.76328'),
              ('lon', '-95.36327'),
              ('name', 'Houston'),
              ('admin1', 'Texas'),
              ('admin2', 'Harris County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.7983'),
              ('lon', '-81.26701'),
              ('name', 'Butler Beach'),
              ('admin1', 'Florida'),
              ('admin2', 'Saint Johns County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.87522'),
              ('lon', '-98.26251'),
              ('name', 'Canyon Lake'),
              ('admin1', 'Texas'),
              ('admin2', 'Comal County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.97854'),
              ('lon', '-90.16396'),
              ('name', 'Metairie Terrace'),
              ('admin1', 'Louisiana'),
              ('admin2', 'Jefferson Parish'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.02274'),
              ('lon', '-82.33956'),
              ('name', 'Lake Butler'),
              ('admin1', 'Florida'),
              ('admin2', 'Union County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '29.99883'),
              ('lon', '-95.26216'),
              ('name', 'Humble'),
              ('admin1', 'Texas'),
              ('admin2', 'Harris County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.21309'),
              ('lon', '-93.2044'),
              ('name', 'Lake Charles'),
              ('admin1', 'Louisiana'),
              ('admin2', 'Calcasieu Parish'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.29495'),
              ('lon', '-82.98402'),
              ('name', 'Live Oak'),
              ('admin1', 'Florida'),
              ('admin2', 'Suwannee County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.23576'),
              ('lon', '-92.09457'),
              ('name', 'Scott'),
              ('admin1', 'Louisiana'),
              ('admin2', 'Lafayette Parish'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.23853'),
              ('lon', '-90.9201'),
              ('name', 'Gonzales'),
              ('admin1', 'Louisiana'),
              ('admin2', 'Ascension Parish'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.26577'),
              ('lon', '-94.19963'),
              ('name', 'Lumberton'),
              ('admin1', 'Texas'),
              ('admin2', 'Hardin County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.33441'),
              ('lon', '-81.3987'),
              ('name', 'Atlantic Beach'),
              ('admin1', 'Florida'),
              ('admin2', 'Duval County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.4427'),
              ('lon', '-97.77501'),
              ('name', 'Jollyville'),
              ('admin1', 'Texas'),
              ('admin2', 'Williamson County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '30.67436'),
              ('lon', '-96.36996'),
              ('name', 'Bryan'),
              ('admin1', 'Texas'),
              ('admin2', 'Brazos County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '31.34102'),
              ('lon', '-83.5935'),
              ('name', 'Omega'),
              ('admin1', 'Georgia'),
              ('admin2', 'Tift County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '31.34656'),
              ('lon', '-89.26006'),
              ('name', 'Petal'),
              ('admin1', 'Mississippi'),
              ('admin2', 'Forrest County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '31.73212'),
              ('lon', '-84.17074'),
              ('name', 'Leesburg'),
              ('admin1', 'Georgia'),
              ('admin2', 'Lee County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.08514'),
              ('lon', '-98.34199'),
              ('name', 'Dublin'),
              ('admin1', 'Texas'),
              ('admin2', 'Erath County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.21769'),
              ('lon', '-82.41346'),
              ('name', 'Vidalia'),
              ('admin1', 'Georgia'),
              ('admin2', 'Toombs County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.22174'),
              ('lon', '-110.92648'),
              ('name', 'Tucson'),
              ('admin1', 'Arizona'),
              ('admin2', 'Pima County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.32341'),
              ('lon', '-110.9951'),
              ('name', 'Casas Adobes'),
              ('admin1', 'Arizona'),
              ('admin2', 'Pima County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.36681'),
              ('lon', '-86.29997'),
              ('name', 'Montgomery'),
              ('admin1', 'Alabama'),
              ('admin2', 'Montgomery County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.51599'),
              ('lon', '-93.73212'),
              ('name', 'Bossier City'),
              ('admin1', 'Louisiana'),
              ('admin2', 'Bossier Parish'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.47098'),
              ('lon', '-85.00077'),
              ('name', 'Phenix City'),
              ('admin1', 'Alabama'),
              ('admin2', 'Russell County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.5007'),
              ('lon', '-94.74049'),
              ('name', 'Longview'),
              ('admin1', 'Texas'),
              ('admin2', 'Gregg County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.60986'),
              ('lon', '-85.48078'),
              ('name', 'Auburn'),
              ('admin1', 'Alabama'),
              ('admin2', 'Lee County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.64541'),
              ('lon', '-85.37828'),
              ('name', 'Opelika'),
              ('admin1', 'Alabama'),
              ('admin2', 'Lee County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.70291'),
              ('lon', '-97.15529'),
              ('name', 'Dalworthington Gardens'),
              ('admin1', 'Texas'),
              ('admin2', 'Tarrant County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.78306'),
              ('lon', '-96.80667'),
              ('name', 'Dallas'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.79652'),
              ('lon', '-96.56082'),
              ('name', 'Sunnyvale'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.81402'),
              ('lon', '-96.94889'),
              ('name', 'Irving'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.85652'),
              ('lon', '-97.33891'),
              ('name', 'Blue Mound'),
              ('admin1', 'Texas'),
              ('admin2', 'Tarrant County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.85791'),
              ('lon', '-97.25474'),
              ('name', 'Watauga'),
              ('admin1', 'Texas'),
              ('admin2', 'Tarrant County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.85791'),
              ('lon', '-97.25474'),
              ('name', 'Watauga'),
              ('admin1', 'Texas'),
              ('admin2', 'Tarrant County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '32.91262'),
              ('lon', '-96.63888'),
              ('name', 'Garland'),
              ('admin1', 'Texas'),
              ('admin2', 'Dallas County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.0343'),
              ('lon', '-83.93824'),
              ('name', 'Forsyth'),
              ('admin1', 'Georgia'),
              ('admin2', 'Monroe County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.0343'),
              ('lon', '-83.93824'),
              ('name', 'Forsyth'),
              ('admin1', 'Georgia'),
              ('admin2', 'Monroe County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.20763'),
              ('lon', '-92.66627'),
              ('name', 'El Dorado'),
              ('admin1', 'Arkansas'),
              ('admin2', 'Union County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.22901'),
              ('lon', '-87.57723'),
              ('name', 'Northport'),
              ('admin1', 'Alabama'),
              ('admin2', 'Tuscaloosa County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.28595'),
              ('lon', '-96.57277'),
              ('name', 'Melissa'),
              ('admin1', 'Texas'),
              ('admin2', 'Collin County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.35283'),
              ('lon', '-111.78903'),
              ('name', 'Gilbert'),
              ('admin1', 'Arizona'),
              ('admin2', 'Maricopa County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.349'),
              ('lon', '-96.5486'),
              ('name', 'Anna'),
              ('admin1', 'Texas'),
              ('admin2', 'Collin County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.52066'),
              ('lon', '-86.80249'),
              ('name', 'Birmingham'),
              ('admin1', 'Alabama'),
              ('admin2', 'Jefferson County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.53865'),
              ('lon', '-112.18599'),
              ('name', 'Glendale'),
              ('admin1', 'Arizona'),
              ('admin2', 'Maricopa County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.53115'),
              ('lon', '-111.94265'),
              ('name', 'Paradise Valley'),
              ('admin1', 'Arizona'),
              ('admin2', 'Maricopa County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.65983'),
              ('lon', '-85.83163'),
              ('name', 'Anniston'),
              ('admin1', 'Alabama'),
              ('admin2', 'Calhoun County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.65983'),
              ('lon', '-85.83163'),
              ('name', 'Anniston'),
              ('admin1', 'Alabama'),
              ('admin2', 'Calhoun County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.86483'),
              ('lon', '-84.46437'),
              ('name', 'Vinings'),
              ('admin1', 'Georgia'),
              ('admin2', 'Cobb County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.871'),
              ('lon', '-79.75535'),
              ('name', 'Lake City'),
              ('admin1', 'South Carolina'),
              ('admin2', 'Florence County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.94121'),
              ('lon', '-84.21353'),
              ('name', 'Norcross'),
              ('admin1', 'Georgia'),
              ('admin2', 'Gwinnett County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.91371'),
              ('lon', '-98.49339'),
              ('name', 'Wichita Falls'),
              ('admin1', 'Texas'),
              ('admin2', 'Wichita County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.99261'),
              ('lon', '-83.72017'),
              ('name', 'Winder'),
              ('admin1', 'Georgia'),
              ('admin2', 'Barrow County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '33.99399'),
              ('lon', '-96.37082'),
              ('name', 'Durant'),
              ('admin1', 'Oklahoma'),
              ('admin2', 'Bryan County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '34.02893'),
              ('lon', '-84.19858'),
              ('name', 'Johns Creek'),
              ('admin1', 'Georgia'),
              ('admin2', 'Fulton County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '34.05223'),
              ('lon', '-118.24368'),
              ('name', 'Los Angeles'),
              ('admin1', 'California'),
              ('admin2', 'Los Angeles County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '34.06635'),
              ('lon', '-84.67837'),
              ('name', 'Acworth'),
              ('admin1', 'Georgia'),
              ('admin2', 'Cobb County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '34.08529'),
              ('lon', '-117.9609'),
              ('name', 'Baldwin Park'),
              ('admin1', 'California'),
              ('admin2', 'Los Angeles County'),
              ('cc', 'US')]),
 OrderedDict([('lat', '34.17934'),
              ('lon', '-77.84748'),

In [7]:
values = np.array([list(d.values()) for d in results2])

In [8]:
values[:,5]

array(['GT', 'PR', 'US', ..., 'US', 'US', 'US'], dtype='<U52')

In [9]:
df["lat"] = values[:,0]

In [10]:
df["lon"] = values[:,1]
df["name"] = values[:,2]
df["admin1"] = values[:,3]
df["admin2"] = values[:,4]
df["cc"] = values[:,5]

In [11]:
df.head()

,dsn,latitude,longitude,created_at,lat,lon,name,admin1,admin2,cc
0,AC000W001151849,14.5333,-91.6833,2019-01-14 00:25:10,14.53611,-91.67778,Retalhuleu,Retalhuleu,Municipio de Retalhuleu,GT
1,AC000W002672712,18.4663,-66.1057,2019-01-14 00:37:49,18.46633,-66.10572,San Juan,San Juan,,PR
2,AC000W001073256,21.4063,-157.7448,2019-01-14 00:31:11,21.40241,-157.74054,Kailua,Hawaii,Honolulu County,US
3,AC000W002437000,24.7279,-81.0386,2019-01-14 00:59:42,24.71375,-81.09035,Marathon,Florida,Monroe County,US
4,AC000W002600666,25.9441,-80.2144,2019-01-14 00:03:32,25.94898,-80.21227,Norland,Florida,Miami-Dade County,US

In [ ]:
# df.admin1[df.cc=="US"].value_counts()

In [13]:
# df.to_csv("GPS_locations.csv", compression="gzip")#, index=False

In [31]:
reader = csv.reader(open('Country codes - cc.csv', 'r'))
d = {}
for cc, un_code in reader:
    d[cc] = int(un_code)

In [32]:
def cc_to_un(x):
    return d[x]

In [39]:
df.cc = df.cc.apply(cc_to_un)

In [40]:
df.head()

,dsn,latitude,longitude,created_at,lat,lon,name,admin1,admin2,cc
0,AC000W001151849,14.5333,-91.6833,2019-01-14 00:25:10,14.53611,-91.67778,Retalhuleu,Retalhuleu,Municipio de Retalhuleu,320
1,AC000W002672712,18.4663,-66.1057,2019-01-14 00:37:49,18.46633,-66.10572,San Juan,San Juan,,630
2,AC000W001073256,21.4063,-157.7448,2019-01-14 00:31:11,21.40241,-157.74054,Kailua,Hawaii,Honolulu County,840
3,AC000W002437000,24.7279,-81.0386,2019-01-14 00:59:42,24.71375,-81.09035,Marathon,Florida,Monroe County,840
4,AC000W002600666,25.9441,-80.2144,2019-01-14 00:03:32,25.94898,-80.21227,Norland,Florida,Miami-Dade County,840

In [2]:
df = pd.read_csv('/Users/brodriguez/Documents/GPS_locations.csv', compression="gzip", index_col=0)

/Users/brodriguez/miniconda3/envs/py36/lib/python3.6/site-packages/numpy/lib/arraysetops.py:522: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
df.head()

,dsn,latitude,longitude,created_at,lat,lon,name,admin1,admin2,cc
0,AC000W001151849,14.5333,-91.6833,2019-01-14 00:25:10,14.53611,-91.67778,Retalhuleu,Retalhuleu,Municipio de Retalhuleu,GT
1,AC000W002672712,18.4663,-66.1057,2019-01-14 00:37:49,18.46633,-66.10572,San Juan,San Juan,NaN,PR
2,AC000W001073256,21.4063,-157.7448,2019-01-14 00:31:11,21.40241,-157.74054,Kailua,Hawaii,Honolulu County,US
3,AC000W002437000,24.7279,-81.0386,2019-01-14 00:59:42,24.71375,-81.09035,Marathon,Florida,Monroe County,US
4,AC000W002600666,25.9441,-80.2144,2019-01-14 00:03:32,25.94898,-80.21227,Norland,Florida,Miami-Dade County,US

In [4]:
df[df.dsn=='AC000W002431442'].sort_values(by='created_at')

,dsn,latitude,longitude,created_at,lat,lon,name,admin1,admin2,cc
1453183,AC000W002431442,26.8760,-82.2681,2018-03-07 20:28:33,26.88368,-82.29009,Rotonda,Florida,Charlotte County,US
1487681,AC000W002431442,26.2888,-81.5300,2018-04-20 23:58:40,26.29286,-81.58842,Orangetree,Florida,Collier County,US
336749,AC000W002431442,28.5445,-81.3706,2018-06-28 15:36:22,28.53834,-81.37924,Orlando,Florida,Orange County,US
1924984,AC000W002431442,27.1870,-81.8713,2018-07-01 18:04:04,27.18629,-81.85210,Southeast Arcadia,Florida,DeSoto County,US
1490392,AC000W002431442,26.6254,-81.6248,2018-08-11 12:52:51,26.62535,-81.62480,Lehigh Acres,Florida,Lee County,US

In [15]:
df.sort_values(by='created_at')

,Unnamed: 0,dsn,latitude,longitude,created_at,lat,lon,name,admin1,admin2,cc
1320829,1320829,AC000W000505647,34.0438,-118.1874,2017-02-23 00:16:18,34.04057,-118.16924,Belvedere,California,Los Angeles County,US
1321162,1321162,AC000W000668811,44.0482,-75.7668,2017-02-23 00:16:27,44.05843,-75.76189,Fort Drum,New York,Jefferson County,US
1321957,1321957,AC000W000671984,42.5860,-83.5006,2017-02-23 00:16:38,42.55670,-83.47383,Wolverine Lake,Michigan,Oakland County,US
1321511,1321511,AC000W000666129,34.9946,-91.8576,2017-02-23 00:16:39,35.07064,-91.87959,Beebe,Arkansas,White County,US
1321128,1321128,AC000W000339053,38.6780,-77.3197,2017-02-23 00:16:39,38.68789,-77.29776,Lake Ridge,Virginia,Prince William County,US
1320802,1320802,AC000W000341858,43.1240,-89.6378,2017-02-23 00:17:33,43.11444,-89.65568,Cross Plains,Wisconsin,Dane County,US
1320883,1320883,AC000W000104975,41.8394,-73.1255,2017-02-23 00:17:54,41.81843,-73.14372,West Torrington,Connecticut,Litchfield County,US
1321280,1321280,AC000W000231835,35.5185,-97.6428,2017-02-23 00:18:14,35.51867,-97.63226,Bethany,Oklahoma,Oklahoma County,US
1321507,1321507,AC000W000102972,42.5386,-123.3478,2017-02-23 00:18:25,42.51734,-123.41979,Merlin,Oregon,Josephine County,US
1322029,1322029,AC000W000258113,38.4412,-121.3064,2017-02-23 00:18:46,38.41186,-121.27217,Wilton,California,Sacramento County,US
1321228,1321228,AC000W000258451,28.7501,-82.5166,2017-02-23 00:20:50,28.73221,-82.50621,Sugarmill Woods,Florida,Citrus County,US
1322075,1322075,AC000W000462323,45.9035,-116.1387,2017-02-23 00:20:52,45.92655,-116.12237,Grangeville,Idaho,Idaho County,US
1321103,1321103,AC000W001122019,34.7172,-80.0975,2017-02-23 00:20:52,34.73599,-80.08812,Chesterfield,South Carolina,Chesterfield County,US
1321177,1321177,AC000W000338353,33.7606,-84.1763,2017-02-23 00:21:03,33.74538,-84.13158,Redan,Georgia,DeKalb County,US
1320900,1320900,AC000W001123409,32.0056,-102.1887,2017-02-23 00:21:12,31.99735,-102.07791,Midland,Texas,Midland County,US
1321587,1321587,AC000W001123454,36.0609,-86.9609,2017-02-23 00:21:44,36.10061,-87.05112,Pegram,Tennessee,Cheatham County,US
1321932,1321932,AC000W000654808,33.6359,-79.0280,2017-02-23 00:21:55,33.59295,-79.00865,Garden City,South Carolina,Horry County,US
1321624,1321624,AC000W000662334,41.9968,-87.7562,2017-02-23 00:21:55,42.00448,-87.73006,Lincolnwood,Illinois,Cook County,US
1321227,1321227,AC000W000336748,27.8489,-82.8282,2017-02-23 00:21:55,27.82614,-82.82899,Redington Shores,Florida,Pinellas County,US
1321232,1321232,AC000W000255002,39.9686,-75.1762,2017-02-23 00:22:06,39.95233,-75.16379,Philadelphia,Pennsylvania,Philadelphia County,US
1322065,1322065,AC000W001082103,40.6583,-111.9231,2017-02-23 00:22:14,40.66772,-111.93883,Taylorsville,Utah,Salt Lake County,US
1322124,1322124,AC000W000257210,33.4910,-86.7369,2017-02-23 00:24:01,33.50094,-86.75221,Mountain Brook,Alabama,Jefferson County,US
1320819,1320819,AC000W000671270,40.1009,-83.0141,2017-02-23 00:25:41,40.09312,-83.01796,Worthington,Ohio,Franklin County,US
1320938,1320938,AC000W000505514,32.3969,-95.4441,2017-02-23 00:25:46,32.49042,-95.45746,Hideaway,Texas,Smith County,US
1320825,1320825,AC000W000364234,41.7606,-84.2282,2017-02-23 00:25:47,41.71949,-84.21800,Morenci,Michigan,Lenawee County,US
1321272,1321272,AC000W000366439,35.1500,-106.5728,2017-02-23 00:26:29,35.17338,-106.62336,North Valley,New Mexico,Bernalillo County,US
1320871,1320871,AC000W001121380,37.7089,-77.5437,2017-02-23 00:27:22,37.66598,-77.50637,Glen Allen,Virginia,Henrico County,US
1320965,1320965,AC000W000447554,36.1659,-86.7844,2017-02-23 00:27:32,36.16589,-86.78444,Nashville,Tennessee,Davidson County,US
2127766,2127766,AC000W000457556,37.7510,-97.8220,2017-02-23 00:30:58,37.63001,-97.78255,Cheney,Kansas,Sedgwick County,US
1321106,1321106,AC000W000332101,46.7440,-92.5739,2017-02-23 00:31:01,46.72161,-92.45936,Cloquet,Minnesota,Carlton County,US
...,...,...,...,...,...,...,...,...,...,...,...
3788,3788,AC000W000364849,33.9352,-85.9576,2019-01-14 20:50:25,33.95704,-85.93247,Glencoe,Alabama,Etowah County,US
3630,3630,AC000W002703124,31.2266,-101.9441,2019-01-14 20:50:43,31.22265,-101.93791,Rankin,Texas,Upton County,US
3663,3663,AC000W002504670,36.1428,-80.3069,2019-01-14 20:50:49,36.09986,-80.24422,Winston-Salem,North Carolina,Forsyth County,US
3668,3668,AC000W001208499,36.7759,-87.3556,2019-01-14 20:51:14,36.66505,-87.44279,Oak Grove,Kentucky,Christian County,US
3698,3698,AC000W001114246,40.2607,-111.6549,2019-01-14 20:51:58,40.23384,-111.65853,Provo,Utah,Utah County,US
3774,3774,AC000W002696117,46.8147,-92.1998,2019-01-14 20:52:11,46.80689,-92.23825,Hermantown,Minnesota,Saint Louis County,US
3699,3699,AC000W001145628,40.2607,-111.6549,2019-01-14 20:53:21,40.23384,-111.65853,Provo,Utah,Utah County,US
3660,3660,AC000W001070743,35.9918,-83.8496,2019-01-14 20:53:33,35.96064,-83.92074,Knoxville,Tennessee,Knox County,US
3665,3665,AC000W002512961,36.1633,-86.6609,2019-01-14 20:53:51,36.24311,-86.63555,Lakewood,Tennessee,Davidson County,US
3776,3776,AC000W002518857,47.4465,-122.1216,2019-01-14 20:53:58,47.44413,-122.09736,Maple Heights-Lake Desire,Washington,King County,US
3772,3772,AC000W002678965,45.7745,-108.5005,2019-01-14 20:54:19,45.78329,-108.50069,Billings,Montana,Yellowstone County,US
3682,3682,AC000W001086949,39.4941,-80.2213,2019-01-14 20:54:25,39.46258,-80.21814,Monongah,West Virginia,Marion County,US
3700,3700,AC000W001064238,40.2607,-111.6549,2019-01-14 20:54:44,40.23384,-111.65853,Provo,Utah,Utah County,US
3636,3636,AC000W003378479,32.4667,35.0000,2019-01-14 20:55:01,32.41562,35.05888,Nazlat `Isa,West Bank,NaN,PS
3740,3740,AC000W002588464,40.7681,-74.0208,2019-01-14 20:55:15,40.76955,-74.02042,Weehawken,New Jersey,Hudson County,US
3783,3783,AC000W002675380,-33.9921,150.8931,2019-01-14 20:55:45,-33.96667,150.90000,Glenfield,New South Wales,Campbelltown Municipality,AU
3790,3790,AC000W000338377,39.5953,-79.9229,2019-01-14 20:55:50,39.61175,-79.90451,Brookhaven,West Virginia,Monongalia County,US
3731,3731,AC000W001064238,40.3958,-111.8506,2019-01-14 20:55:54,40.39162,-111.85077,Lehi,Utah,Utah County,US
3659,3659,AC000W002517656,35.9878,-115.1167,2019-01-14 20:56:26,36.07081,-115.08416,Whitney,Nevada,Clark County,US
3632,3632,AC000W002459728,32.0738,-82.9146,2019-01-14 20:56:38,32.07379,-82.91459,Helena,Georgia,Telfair County,US
3751,3751,AC000W002449764,41.5695,-93.7994,2019-01-14 20:56:54,41.60304,-93.72411,Clive,Iowa,Polk County,US
3655,3655,AC000W002600689,34.9441,-89.8544,2019-01-14 20:57:26,34.96176,-89.82953,Olive Branch,Mississippi,De Soto County,US
3732,3732,AC000W001154341,40.3958,-111.8506,2019-01-14 20:57:39,40.39162,-111.85077,Lehi,Utah,Utah County,US
3680,3680,AC000W001086949,39.2874,-80.3419,2019-01-14 20:58:18,39.28065,-80.34453,Clarksburg,West Virginia,Harrison County,US
3744,3744,AC000W002525070,41.1619,-85.4737,2019-01-14 20:58:36,41.15727,-85.48831,Columbia City,Indiana,Whitley County,US
3701,3701,AC000W003420138,40.2607,-111.6549,2019-01-14 20:58:37,40.23384,-111.65853,Provo,Utah,Utah County,US
3702,3702,AC000W001204445,40.2607,-111.6549,2019-01-14 20:58:42,40.23384,-111.65853,Provo,Utah,Utah County,US
3621,3621,AC000W001111600,25.0833,-77.3500,2019-01-14 20:59:24,25.05823,-77.34306,Nassau,New Providence,NaN,BS
2077124,2077124,AC000W002450163,37.7510,-97.8220,2019-01-14 20:59:30,37.63001,-97.78255,Cheney,Kansas,Sedgwick County,US
3733,3733,AC000W003420138,40.3958,-111.8506,2019-01-14 20:59:39,40.39162,-111.85077,Lehi,Utah,Utah County,US

## Dsns in United states

In [34]:
dsns_in_us = set(df[df.cc == 'US'].dsn.values) #Unique dsns

In [35]:
len(dsns_in_us)

234269

In [36]:
# total dsns with location
len(set(df.dsn.values))

249792